// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZ-rzM9RE_MZIQ8xMkJxhHuNSuyrY1Jo',
    appId: '1:318263045768:web:131f28b18845c01cac793d',
    messagingSenderId: '318263045768',
    projectId: 'digital-waiter-5dbd1',
    authDomain: 'digital-waiter-5dbd1.firebaseapp.com',
    storageBucket: 'digital-waiter-5dbd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8hN_NKHp67XY1uhGFHYlq75iDgHTxdbU',
    appId: '1:318263045768:android:f75851f2f70dd798ac793d',
    messagingSenderId: '318263045768',
    projectId: 'digital-waiter-5dbd1',
    storageBucket: 'digital-waiter-5dbd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSxv8Ud5sKof-asg7vKzUVkP1qUdD4Sk0',
    appId: '1:318263045768:ios:5af81743de012d3dac793d',
    messagingSenderId: '318263045768',
    projectId: 'digital-waiter-5dbd1',
    storageBucket: 'digital-waiter-5dbd1.firebasestorage.app',
    iosBundleId: 'com.example.digitalWaiter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSxv8Ud5sKof-asg7vKzUVkP1qUdD4Sk0',
    appId: '1:318263045768:ios:5af81743de012d3dac793d',
    messagingSenderId: '318263045768',
    projectId: 'digital-waiter-5dbd1',
    storageBucket: 'digital-waiter-5dbd1.firebasestorage.app',
    iosBundleId: 'com.example.digitalWaiter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPZ-rzM9RE_MZIQ8xMkJxhHuNSuyrY1Jo',
    appId: '1:318263045768:web:6b9623b0317850c3ac793d',
    messagingSenderId: '318263045768',
    projectId: 'digital-waiter-5dbd1',
    authDomain: 'digital-waiter-5dbd1.firebaseapp.com',
    storageBucket: 'digital-waiter-5dbd1.firebasestorage.app',
  );
}
